-- Display contents of the Users table
SELECT * FROM Users;

-- Display contents of the RoomTypes table
SELECT * FROM RoomTypes;

-- Display contents of the Rooms table
SELECT * FROM Rooms;

-- Display contents of the Activities table
SELECT * FROM Activities;

-- Display contents of the Bookings table
SELECT * FROM Bookings;

-- Display contents of the Confirmations table
SELECT * FROM Confirmations;

-- Display contents of the Billing table
SELECT * FROM Billing;

-- Display contents of the Logs table
SELECT * FROM Logs;
